### ISSUE TITLE
canola oil puddle crash

### ISSUE THREAD

**Issue by wesleybruce** [ricksouth/serilum-mc-mods#783] opened 2021-11-17 15:35 UTC
## **Information**
Minecraft version: 1.17.5
Modloader: Forge 
Forge version: 37.0.109  
Environment: Singleplayer 

Mod name: Mod Eroding Stone Entities (Forge)
Mod version: 2.4 

## **Description**
I Accidently placed canola oil from the ultimate car mod in world. It caused a crash that was fixed by de-activating your mod. There is no flowing version of canola but it seems your mod is trying to use it as a flowing fluid.  Note that mod has methanol, glycerol and biodiesel. All three may also trigger the error. I have reported it to the ultimate car mod. It would be very nice if you guys could  perhaps collaborate and make it flow and do something creative. That mod needs a lot of iron. Otherwise just code it so we don't get a crash. 

## **Crash report**
If available
[crash-2021-11-18_01.12.09-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/7555784/crash-2021-11-18_01.12.09-client.txt)
.

**Comment by James103** [comment] 2021-11-17 20:59
1. Did you mean "Minecraft 1.17.1"? If so, please update that line in your issue description.
2. Can you please link the corresponding issue from the ultimate car mod?

**Comment by ricksouth** [comment] 2021-11-22 18:46
Seems like the problem is within Forge:
https://github.com/MinecraftForge/MinecraftForge/issues/7922

Closing this here for now.

**Closed as completed by ricksouth** 2021-11-22 18:46 UTC
Labels: Bug, Mod: Eroding Stone Entities
