### ISSUE TITLE
[Suggestion] Village Spawn Point - include/exclude specific buildings

### ISSUE THREAD

**Issue by Sarsath** [ricksouth/serilum-mc-mods#1249] opened 2022-08-12 01:45 UTC
## **Information**
Mod name: Village Spawn Point

## **Feature description**
It would be fabulous if you had the ability to spawn in a village that meets your criteria. For example, if you do not want to spawn in a village with a mason building, you can configure the mod so you spawn in villages without mason buildings. The options in the configure menu could be "Include", "Exclude", and "I don't care".

**Comment by James103** [comment] 2022-08-12 01:47
Duplicate of #432

**Comment by ricksouth** [comment] 2022-08-15 18:11
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Closed as not planned by ricksouth** 2022-08-15 18:11 UTC
Labels: Feature Request, Mod: Village Spawn Point

**Comment by ricksouth** [comment] 2024-01-07 15:17
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
