### ISSUE TITLE
Cant change configuration "mustHaveItemsInInventoryForCreation" 

### ISSUE THREAD

**Issue by mateoromero2000** [ricksouth/serilum-mc-mods#1200] opened 2022-07-26 02:11 UTC
I set the mod's "Your Items Are Safe" configuration "mustHaveItemsInInventoryForCreation" to false and it doesn't work (it still doesnt make a chest when i without having the necessary materials
![Screenshot 2022-07-25 231050](https://user-images.githubusercontent.com/107862923/180907522-25c6fb7c-e4f1-4a18-8adc-9185b6891de5.png)
)

**Comment by James103** [comment] 2022-07-26 02:36
Duplicate of #1201

**Comment by mateoromero2000** [comment] 2022-07-26 02:39
sorry, I tried deleting this one since I created another issue of the same error with more info, but I don't know how to delete this one :).

**Closed as completed** 2022-08-02 17:13 UTC
