### ISSUE TITLE
Replanting Crops doesn't harvest & replant

### ISSUE THREAD

**Issue by John2022** [ricksouth/serilum-mc-mods#824] opened 2021-12-07 02:51 UTC
## **Information**
Minecraft version: 1.18 (vanilla + 3 mods in mods folder)
Modloader: Fabric 
Fabric loader version: 0.10.2
Environment: Singleplayer

Mod name: Collective Lib. v3.13 (Fabric)
Mod name: Fabric API v0.44.0
Mod name: Replanting Crops v2.5 (Fabric)

## **Description**
When attempt to harvest, the crops disappear, but no replanting (even with "mustHoldHoeForReplanting": false ), nor items poped.
+The bloc stay in a destruction level
+Right clic make the crop reappears as it was before the harvest task.

## **Crash report**
No crach, but here's the log
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7665148/latest.log)
:

**Comment by lilbman92** [comment] 2021-12-23 20:57
Same issue currently.. my treehavester, and inventory sorter is working on my private server. I have fabric api along with collective.. I change the hoe harvest to false and true but still didnt work either way.. I also have Fabric API v0.45.0, and collective v.3.14

**Comment by markygnlg** [comment] 2022-03-26 04:10
WORKED until I added the xumavoid's data & res packs (I'll post here & the other 'issues' post).

This mod worked as intended until I added a datapack/respack combo from xumavoids 'vanilla tweaks' page. I added several at the same time so I don't know what caused this mod to fail but I can give a list of both the data & res packs as they both include a 'Selected Pack' text file with a list of what i added/included.

mc: 1.18.1
forge: 39.1.0
mod: replantingcrops_1.18.1-2.6.jar
req mod: collective-1.18.1-4.7.jar

... however the versions are irrelevant as this mod worked until I added the xumavoid stuff

**Comment by markygnlg** [comment] 2022-03-26 04:24
..to be clearer:
1. worked with default settings ONLY with a hoe tool;
2. worked without a tool after editing 'mustHoldHoeForReplanting' to 'false'
... I'll paste the respack text file list included in the zip (keep in mind that I also have both graphic & recipe datapacks from that xumavoid website too)...

- VanillaTweaks_r737420.zip -> 'Selected Packs.txt'

	NumberedHotbar
	LargeAttackIndicator
	UnobtrusiveScaffolding
	LowerFire
	LowerShield
	TransparentPumpkin
	BuddingAmethystBorders
	Age25Kelp
	FullAgeAmethystMarker
	DirectionalHoppers
	DirectionalDispensersDroppers
	BetterObservers
	StickyPistonSides
	RedstonePowerLevels
	UnlitRedstoneOre
	VisibleTripwires
	GroovyLevers
	BrewingGuide
	VisualHoney
	VisualCauldronStages
	NoteblockBanners
	VisualSaplingGrowth
	VisualComposterStages
	OreBorders
	QuieterCows
	QuieterDispensersDroppers
	QuieterNetherPortals
	QuieterGhasts
	QuieterVillagers
	QuieterPistons
	QuieterRain
	QuieterWater
	QuieterFire
	VariatedDirt
	VariatedGrass
	VariatedCobblestone
	VariatedBricks
	VariatedLogs
	VariatedMushroomBlocks
	VariatedPlanks
	VariatedGravel
	VariatedBookshelves
	RandomSunflowerRotation
	VariatedUnpolishedStones
	LowerGrass
	LowerMycelium
	LowerPaths
	LowerPodzol
	LowerSnow
	LowerCrimsonNylium
	LowerWarpedNylium
	WavyWater
	ShorterGrass
	ShorterTallGrass
	3DLadders
	3DSunMoon
	3DVines
	GlassTrapdoors
	GlassDoors
	UniqueDyes
	PolishedStonesToBricks
	FullAgeCropMarker
	DifferentStems

**Comment by markygnlg** [comment] 2022-03-26 04:30
as OP mentioned: ".. attempt to harvest .. crops disappear .. no replanting .. Right clic make the crop reappear"

same for me AFTER I added the xumavoid/vanilla tweaks stuff

**Comment by burt245** [comment] 2022-05-15 07:29
this wasnt caused by any incompatibility, the last update broke the mod.
downgrading to 2.4 fixes it.

**Comment by ricksouth** [comment] 2022-09-05 18:26
This should be fixed in version 4.0. Please let me know if it isn't the case. Thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/replanting-crops-fabric

**Closed as completed by ricksouth** 2022-09-05 18:26 UTC
Labels: Bug, Mod: Replanting Crops, Modloader: Fabric
