### ISSUE TITLE
It just isn't working.

### ISSUE THREAD

**Issue by Killallplayers** [ricksouth/serilum-mc-mods#920] opened 2022-01-30 22:09 UTC
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.59
Environment: Singleplayer

Mod name: Replanting Crops
Mod version: 2.6

## **Description**
Basically I downloaded collective and then I went into the game. I even followed the steps to make it so I don't need a hoe. And nothing happened anyway. not even plants would drop it just dissapeared.

## **Crash report**
If available.

**Comment by James103** [comment] 2022-01-30 23:19
Can you please post the full mod list?

**Comment by Killallplayers** [comment] 2022-01-30 23:29
> Can you please post the full mod list?
![delete](https://user-images.githubusercontent.com/94154895/151722403-c6644a62-46f1-4ce6-80ac-1a691c877a0b.png)

**Comment by markygnlg** [comment] 2022-03-26 04:10
WORKED until I added the xumavoid's data & res packs (I'll post here & the other 'issues' post).

This mod worked as intended until I added a datapack/respack combo from xumavoids 'vanilla tweaks' page. I added several at the same time so I don't know what caused this mod to fail but I can give a list of both the data & res packs as they both include a 'Selected Pack' text file with a list of what i added/included.

mc: 1.18.1
forge: 39.1.0
mod: replantingcrops_1.18.1-2.6.jar
req mod: collective-1.18.1-4.7.jar

... however the versions are irrelevant as this mod worked until I added the xumavoid stuff

**Comment by markygnlg** [comment] 2022-03-26 04:25
..to be clearer:

worked with default settings ONLY with a hoe tool;
worked without a tool after editing 'mustHoldHoeForReplanting' to 'false'
... I'll paste the respack text file list included in the zip (keep in mind that I also have both graphic & recipe datapacks from that xumavoid website too)...
VanillaTweaks_r737420.zip -> 'Selected Packs.txt'

NumberedHotbar
LargeAttackIndicator
UnobtrusiveScaffolding
LowerFire
LowerShield
TransparentPumpkin
BuddingAmethystBorders
Age25Kelp
FullAgeAmethystMarker
DirectionalHoppers
DirectionalDispensersDroppers
BetterObservers
StickyPistonSides
RedstonePowerLevels
UnlitRedstoneOre
VisibleTripwires
GroovyLevers
BrewingGuide
VisualHoney
VisualCauldronStages
NoteblockBanners
VisualSaplingGrowth
VisualComposterStages
OreBorders
QuieterCows
QuieterDispensersDroppers
QuieterNetherPortals
QuieterGhasts
QuieterVillagers
QuieterPistons
QuieterRain
QuieterWater
QuieterFire
VariatedDirt
VariatedGrass
VariatedCobblestone
VariatedBricks
VariatedLogs
VariatedMushroomBlocks
VariatedPlanks
VariatedGravel
VariatedBookshelves
RandomSunflowerRotation
VariatedUnpolishedStones
LowerGrass
LowerMycelium
LowerPaths
LowerPodzol
LowerSnow
LowerCrimsonNylium
LowerWarpedNylium
WavyWater
ShorterGrass
ShorterTallGrass
3DLadders
3DSunMoon
3DVines
GlassTrapdoors
GlassDoors
UniqueDyes
PolishedStonesToBricks
FullAgeCropMarker
DifferentStems

**Comment by markygnlg** [comment] 2022-03-26 04:27
as OP mentioned: **'not even plants would drop it just dissapeared.'**

same for me AFTER I added the xumavoid/vanilla tweaks stuff

**Comment by Killallplayers** [comment] 2022-08-20 05:29
> same for me AFTER I added the xumavoid/vanilla tweaks stuff

Thanks so much! :D

**Comment by markygnlg** [comment] 2022-08-20 05:52
might be a good idea to mark this as '**solved**' since it's a compatibility issue rather than a bug (ie. it works as intended)
 ... or you might be able to change the tag/label to '**Compatibility issue**' instead of '**A Bug**' (although the labels/tags might only be allowed to be changed by the moderators).

**Comment by markygnlg** [comment] 2022-08-20 05:53
... & you're welcome
 (or is it 'welcomed' - past tense?).

**Comment by ricksouth** [comment] 2022-09-05 18:26
This should be fixed in version 4.0. Please let me know if it isn't the case. Thanks for giving the mod a try! Thanks @markygnlg for the research.

https://www.curseforge.com/minecraft/mc-mods/replanting-crops

**Closed as completed by ricksouth** 2022-09-05 18:26 UTC
Labels: Bug, Mod: Replanting Crops
