### ISSUE TITLE
Nether Portal Spread prevention blocks

### ISSUE THREAD

**Issue by phntsm** [ricksouth/serilum-mc-mods#1158] opened 2022-07-09 13:51 UTC
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.7
Environment: Singleplayer

Mod name: Nether Portal Spread
Mod version: 5.7

## **Question**
Hello, I was editing some of the configs for this mod and was curious about preventSpreadBlockString, is it possible to list multiple block IDs but have it so that any of the listed blocks with combined AmountNeeded will prevent spread? For example, I set AmountNeeded to two and then add IDs for ancient debris, crying obsidian, deepslate gold ore, polished deepslate, gilded blackstone and lodestone. As long as I place two total blocks in any variation of those listed it prevents spread? I apologize if that is already the intended outcome. If not, is there a special way to add multiple IDs to the string? Thank you very much for all of your great QoL mods, they've definitely renewed Minecraft for me. Cheers!

**Comment by ricksouth** [comment] 2022-08-15 17:00
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Closed as not planned by ricksouth** 2022-08-15 17:00 UTC
Labels: Feature Request, Mod: Nether Portal Spread

**Comment by ricksouth** [comment] 2024-01-07 15:15
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!

**Comment by Greg-21** [comment] 2025-03-22 10:30
This is basically a duplicate of #886.

@phntsm, if you're still interested in having this implemented like I am, please upvote the linked GitHub issue.
