### ISSUE TITLE
Crash when destroying a minecart with double doors installed

### ISSUE THREAD

**Issue by BLUEChester** [ricksouth/serilum-mc-mods#1739] opened 2023-04-29 09:45 UTC
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric (Quilt)
Fabric loader version: 0.18.10
Environment: Singleplayer

Mod name: Double Doors
Mod version: 4.5

Description:
Whenever I destroy a minecart the mod crashes my game, this happened consistently, and every single time I destroy a minecart. The reason I believe it is the double doors mod causing it is because I tried removing all my mods from the game and after removing this mod the issue was resolved.

Edit: After more testing, I believe it could be a compatibility issue with [Horse Stonks](https://modrinth.com/mod/horse-stonks) as removing either double doors or horse stonks resolved the issue. 

Thanks for your work on your mods, I especially love weaker spider webs and double doors! Keep up the great work.

## **Crash report**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/11358823/latest.log)

[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/11358825/debug.log)

**Comment by ricksouth** [comment] 2023-06-23 09:23
I have tested it and am unable to reproduce the issue. Though I have just released version 5.0 of Double Doors. Closing this for now, but please let me know if the problem persists. And maybe also open an issue with Horse Stonks. I can't find anything related to the Double Doors mod in the logs you provided. Thanks for giving the mod a try!

**Closed as completed by ricksouth** 2023-06-23 09:23 UTC
Labels: Bug, Mod: Double Doors
