### ISSUE TITLE
Visual bug on 1.18.1 when multiple stacks of item are present in inventory

### ISSUE THREAD

**Issue by LegendaryTot** [ricksouth/serilum-mc-mods#868] opened 2021-12-24 21:29 UTC
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.8
Environment: Singleplayer

Mod name: Stack Refill
Mod version: 2.1

## **Description**
I noticed if I have multiple stacks of items in my inventory (i.e. Gold blocks that are spread out) the stack refill causes a bug where the item appears invisible in my hotbar when it's refilled. I tested in a clean environment with no other mods other than this one.

Here's GIF of the problem: https://imgur.com/a/Qnsv2M0

**Comment by Raidobw2** [comment] 2022-02-25 14:16
I have the same issue! :o It only happens for stacks that are dragged to the hotbar that contain only one item. They are in fact put on the slot but don't show up on the client. Stacks of 2 items and more are transferred just fine as well and show up correctly. The issue is likely to be client side.
## Versions
Minecraft `1.18.1`
Forge `39.0.79`
Stack Refill: `stackrefill_1.18.1-2.1.jar`
Lib: `collective-1.18.1-4.7.jar`
## Screenshots
See gif below
![stack_refill_ghost_item](https://user-images.githubusercontent.com/17010632/155729655-1d16e8af-27c3-46c5-9691-a197c7825165.gif)
## Additional Info
Thanks in advance for checking it out when you get some time, and have a good day.

**Comment by ricksouth** [comment] 2022-09-20 20:40
Thanks for opening the issue and giving the mod a try! Apologies this took so long for me to get to. This has been fixed in version 3.0 of Stack Refill.

https://www.curseforge.com/minecraft/mc-mods/stack-refill

**Closed as completed by ricksouth** 2022-09-20 20:40 UTC
Labels: Bug, Mod: Stack Refill

**Comment by Raidobw2** [comment] 2022-09-21 08:02
Thanks a lot! Have a good day
