### ISSUE TITLE
[Crash] "treeharvester Crash on entering Tardis Refined interior for first time

### ISSUE THREAD

**Issue by AlienXtream** [ricksouth/serilum-mc-mods#1521] opened 2023-01-08 08:57 UTC
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.3
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: 1.19.2-7.0 (and older versions)

## **Description**
as title says, upon enter

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment] 2023-01-08 09:04
Do you have the crash log for me?

**Comment by ricksouth** [comment] 2023-01-08 09:06
Duplicate of https://github.com/ricksouth/serilum-mc-mods/issues/1522

**Closed as completed** 2023-01-08 09:07 UTC
Labels: Mod: Tree Harvester, Incompatibility
