### ISSUE TITLE
Is It Compatible With Fabric?

### ISSUE THREAD

**Issue by LevelNaomi** [ricksouth/serilum-mc-mods#585] opened 2021-06-04 02:56 UTC
so i wanted to put this in my fabric server but i dont know if it works with fabric

**Comment by James103** [comment] 2021-06-04 03:01
From the FAQ:
> **- Can you release a Fabric version for all of your mods?**
> * I'm keeping it in mind, but for now I don't have plans for a fabric version. With the current infrastructure it would mean having another 100+ projects pages. Maybe if in the future a better separation in the file upload section exists, I'll consider it again.

In other words, all of Ricksouth's mods are currently Forge only for the time being.

Also duplicate of #183, #219, #250, and similar issues.

**Closed** 2021-06-27 17:42 UTC
Labels: A Question
