### ISSUE TITLE
Config file doesn't do anything

### ISSUE THREAD

**Issue by nbtc971** [ricksouth/serilum-mc-mods#1822] opened 2023-06-17 04:05 UTC
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 1.14.21
Environment: Multiplayer

Mod name: Double Doors
Mod version: 3-4.5

## **Description**
Double fence gates still opening and closing when I disable it in the config file on both server and client.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment] 2023-06-23 09:23
I have tested it and am unable to reproduce the issue. Though I have just released version 5.0 of Double Doors. Closing this for now, but please let me know if the problem persists. Thanks for giving the mod a try!

**Closed as completed by ricksouth** 2023-06-23 09:23 UTC
Labels: Bug, Mod: Double Doors
