### ISSUE TITLE
Trades Locking

### ISSUE THREAD

**Issue by Potatomonium** [ricksouth/serilum-mc-mods#879] opened 2021-12-31 23:19 UTC
## **Information**
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: 39.0.9  
Environment: Dedicated Multiplayer Server

Mod name: Infinite Trading 
Mod version: 1.18.1-2.0

## **Description**
I updated to Forge 39.0.9, Updated the Jade mod version 1.18-4.1.0 and installed the mod Infinte Music mod since last trading with a villager. The trades started locking with a message on the cross of "Villagers restock up to two times per day"

I'm also using the Trading Post mod, but it has been fine previously

**Comment by Thiana** [comment] 2021-12-31 23:22
Duplicate of #864

**Comment by ricksouth** [comment] 2022-09-06 18:14
This has been fixed in version 3.0 of Infinite Trading. It has completely been rewritten. How the offers are reset has changed and it now accounts for demand correctly. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading/

**Closed as completed by ricksouth** 2022-09-06 18:14 UTC
Labels: Bug, Mod: Infinite Trading
